name: Build Disc-Out

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Rebuild better-sqlite3
        run: npx electron-rebuild -f -w better-sqlite3

      - name: Build Windows installer
        run: npm run make

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: Disc-Out-Windows
          path: out/make/**
          if-no-files-found: error


  build-macos:
    name: Build macOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Rebuild better-sqlite3
        run: npx electron-rebuild -f -w better-sqlite3

      - name: Build macOS installer
        run: npm run make

      - name: Upload macOS build
        uses: actions/upload-artifact@v4
        with:
          name: Disc-Out-macOS
          path: out/make/**
          if-no-files-found: error